### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by KevinDanikowski** [zjael/proxy-balancer#23]
# Max retry / retryIf function

Description: There should be a rule for max retries, or even an exposed function for handling retries. One option would be to retry the same proxy X times before moving on to another. An exposed function would look like retryIf: `({retryCount, currentIPRetryCount, IPsRetried}) => {... do stuff ... return 'next' (Enum of ['retry', 'next', 'stop'])`

# timeout after X calls

Description: though most use cases are served with a flat timeout of X seconds, it would be useful to have a timeout after X calls (ideally in Z seconds) it should timeout for Y seconds. For example after 100 calls made within 1 minute it should timeout for 5 minutes.

# option to extend bottleneck config

Description: Perhaps there is a use case where someone would like to add additional configs to the bottle neck. This is a quick 2 second change.

# change proxy array from string array to object array

Description: Some users would like to add auth. It would be convenience to add this auth to protect the proxy endpoints.

# option to switch request agent

Description: Some users may wish to use axios, got, or various other request libraries

**Comment by zjael** [comment]
All good suggestions, i can see you already started working on it, looks good 😀
I don't know about changing from string array to object array, we could just do:
"http://user:password@0.0.0.0:8080", which is pretty standard format that curl uses too.
simple-proxy-agent supports it already, so should be working as expected currently, though missing in readme.

**Comment by KevinDanikowski** [comment]
@zjael Thanks for the reply! Haha, yes I started implementing most of these already. I'm having some trouble with timeout after X calls but I found a good package to manage that so I'm going to keep trying to add support for it. And I didn't add "and option to use your own proxy agent", but in order to support this effectively, the values will need to be strings. I've added the object part additively so you can pass an array of strings or array of objects. The nice part about passing objects is the agent creation function (defaulting to your simple-proxy-agent), where you need to access objects in some cases instead of just urls, will work now with agents that require more than just the string.

My next item on my list is the retryIf function, add tests for that, and I should be ready to make a PR that we can discuss.

**Comment by zjael** [comment]
@KevinDanikowski Sounds good, i like the optional array method 😉 Looking forward to the PR 😃

**Comment by KevinDanikowski** [comment]
@zjael  I meant to ask one question, what is this delay for? Is it just to wait 200ms incase the original get proxies call returns earlier?

if (this.fetchingProxies) {
    if (this.proxies.length > 0) {
      return this.proxies;
    }
    await delay(200); // here
    return this.getProxies();
  }

**Comment by zjael** [comment]
@KevinDanikowski it's to spare the cpu, if multiple requests gets sent at once, they will all wait for the getProxies to complete, in a infinite loop. There might be better ways to solve it, so feel free to play around with it. 😉
